name: rich_food
description: "Distribution System"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  double_back_to_close: ^2.0.0
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  google_nav_bar: ^5.0.6
  get: ^4.6.6
  logger: ^2.3.0
  lottie: ^3.1.2
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.1.2
  get_storage: ^2.1.1
  sqflite: ^2.3.2
  path: ^1.8.3
  avatar_glow: ^3.0.1
  url_launcher: ^6.3.0
  # ...............
  # flutter_map: ^7.0.2
  # latlong2: ^0.9.1
  # geolocator: ^12.0.0


  #  calendar_date_picker2: ^0.5.3
  #  mobile_scanner: ^3.5.5
  #  image_collage: ^0.0.4
  #  flutter_rating_bar: ^4.0.1
  #  image_picker: ^1.0.7
  #  animated_custom_dropdown: ^2.0.0
  #  file_picker: ^8.0.0+1
  #  flutter_file_downloader: ^1.2.1
  #  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
#  flutter_launcher_icons: ^0.13.1

#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/logo_icon.png"

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/json/


  fonts:
    - family: 'Noto Kufi Arabic'
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoKufiArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoKufiArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
          weight: 700

    - family: RichFood
      fonts:
        - asset: assets/fonts/RichFood.ttf